### ISSUE TITLE
Mednafen accurate pce module

### ISSUE THREAD

**Issue by OmegaXII** [libretro/beetle-pce-fast-libretro#19]
It would be nice if the "accurate" Mednafen pce module was ported to libretro so it could be an option for faster hardware alongside the existing pce-fast module

**Comment by eadmaster** [comment]
I definitively second the request!

**Comment by SigmaVirus** [comment]
I third the request times thousand!

I would rather have seen the accurate core/module being ported then the fast one and I'm all in for accuracy no matter the cost.

It would easily have been my PC-Engine emulator of choice like the Mednafen PSX libretro core is for PlayStation.

Oh well, maybe one day...

**Comment by SedrynTyros** [comment]
I think this is long overdue

**Comment by DukeSkinny** [comment]
Indeed this would be the optimal scenario, unless a technical explanation is given as to why it would be unfeasible.

**Comment by SigmaVirus** [comment]
@SedrynTyros @DukeSkinny 

Yes it is long overdue and a lot have happened since 2015/2016, too much in fact.

I'm using standalone Mednafen these days for the accurate PC Engine module, have been since last fall and I have given up hope on this a long time ago now.

I suggest anyone else having dreams of a accurate PC Engine core in RetroArch to give up hope too, it's not coming and there is absolutely 0 interest in making it.

@OmegaXII 
You can close this issue, there will never be a accurate PC Engine core and the developers obviously have no interest in this.

**Comment by sljunkie** [comment]
So far mednafen's Accurate PCE core is the best PCE emulator out there so yes I fifth / sixth the request.

**Comment by retro-wertz** [comment]
without libretro able to handle ***multi-width modes** for each frame, then having an accurate core wouldnt make significant difference...

*(forgot the exact term but pce is able to render for example main game screen in different with than the status bar for example)

**Comment by fr500** [comment]
I figure the end result is a standard with though right?

**Comment by trinemark** [comment]
I thought it was a pain to get it ported. Built on top of Beetle PCE Fast as it was easier than doing the brute force approach from scratch. Didn't see anything useful added up to 1.22.1 other than unwanted new api overhead.

Mednafen 0.9.48 (accurate) core
https://github.com/trinemark/beetle-pce-fast-libretro/tree/pce

It lacks some (debugger code) removal cleanups, uses owl resampler (adpcm, psg), misses some options like multiple par, hq adpcm, disable multitap, dshadoff cdrom fixes (https://github.com/dshadoff/mednafen-debug), correct 565 color expansion, framebuffer reduction, and other misc stuff I wanted to do.

Tested on several games:
- Bonk's Adventure. Just testing core even works.
- 1941 - Counter Attack. Super Grafx (sgx) works.
- Daimakaimura. Super Grafx (pce) okay.
- Violent Soldier. No expanding scanline garbage on stage 1.
- Popful Mail (cue). No cutscene garbage.
- D&D: Order of the Griffin. Dungeon view stretches correctly (mid-frame resolution changes).
- Final Blaster. Cutscenes show panels correctly.

No plans to work on this for awhile. If Team Libretro takes over core ownership and future development, that'd be more great.

**Comment by hizzlekizzle** [comment]
@trinemark well that's awesome. Thanks for this!

**Comment by Tatsuya79** [comment]
I fail to compile it with MSYS2 gcc7.3 on win7 x64:

```cpp
In file included from mednafen/pce/huc.cpp:28:0:
mednafen/pce/mcgenjin.h:169:7: error: 'unique_ptr' in namespace 'std' does not name a template type
  std::unique_ptr<MCGenjin_CS_Device> cs[2];
       ^~~~~~~~~~
mednafen/pce/mcgenjin.h: In member function 'uint8 MCGenjin::ReadTP(int32, uint32)':
mednafen/pce/mcgenjin.h:89:18: error: 'cs' was not declared in this scope
    case 2: ret = cs[0]->Read(timestamp, A & 0x3FFFF); break;
                  ^~
mednafen/pce/mcgenjin.h: In member function 'void MCGenjin::WriteTP(int32, uint32, uint8)':
mednafen/pce/mcgenjin.h:136:19: error: 'cs' was not declared in this scope
    case 2: return cs[0]->Write(timestamp, A & 0x3FFFF, V);
                   ^~
mednafen/pce/mcgenjin.h:136:57: error: return-statement with a value, in function returning 'void' [-fpermissive]
    case 2: return cs[0]->Write(timestamp, A & 0x3FFFF, V);
                                                         ^
mednafen/pce/mcgenjin.h:137:57: error: return-statement with a value, in function returning 'void' [-fpermissive]
    case 3: return cs[1]->Write(timestamp, A & 0x3FFFF, V);
                                                         ^
make: *** [Makefile:600: mednafen/pce/huc.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from ./mednafen/hw_video/huc6270/vdc.h:4:0,
                 from mednafen/pce/vce.h:22,
                 from libretro.cpp:17:
./mednafen/lepacker.h: In member function 'void MDFN::LEPacker::operator^(T&)':
./mednafen/lepacker.h:51:16: error: 'out_of_range' is not a member of 'std'
     throw(std::out_of_range("LEPacker::operator^"));
                ^~~~~~~~~~~~
make: *** [Makefile:600: libretro.o] Error 1
```

**Comment by trinemark** [comment]
@Tatsuya79
I was fishing around on how to compute the exact system fps using snes timing notes but forgot to replace the numbers. Don't have the exact number yet so I'll revert that back to what it was ~59.98.

unique_ptr = c++14. I was aiming to remove all c++11 and beyond stuff, including that throw. MSVC 2017 auto-compiles with c++14 or c++17 I guess.

Thanks. I'll get up and start working on this now. Maybe get some more stuff done first before hanging it up again.

@hizzlekizzle
If the bounty owners wish to donate directly to libretro or any emu author, that'd be preferred. I myself won't be collecting on it.

**Comment by trinemark** [comment]
@Tatsuya79
Try new commit. Should build on Linux too.
https://github.com/trinemark/beetle-pce-fast-libretro/tree/pce

Will add more commits as I get to them.

**Comment by Tatsuya79** [comment]
Thanks it compiles fine now! :+1: :smiley:

**Comment by Tatsuya79** [comment]
It works quite decently already, some issues I noticed:
-PSG volume not working
-horizontal overscan not working (games like ninja spirit stay at 341 pixels width)
-overclock not working (sprite limit too?)
-some garbage in the overscan on bottom (especially noticeable in vertical shmups, when setting max 242px, or redraws in Sylphia)
-order of the gryphon is setting the picture to 341 width, so top picture is squished (noticeable on fonts during dialogues)
-sound clicks at the end of a sample (like the upgraded sword hit effect in ninja spirit)

**Comment by trinemark** [comment]
Do you have a small list where to check overclock, sprite limit, psg volume, etc? Testing multitap disable and 12-bit adpcm. Have to check Mednafen options and compare to Beetle core.

**Comment by Tatsuya79** [comment]
PSG volume (only for cd games), I go into Sylphia sound test. 
But any CD game basic sound effects are PSG. You can test with pce_fast/sgx 1st to make sure.

For overclock I usually test with ninja spirit. 
Stage 1 end boss when ninjas jump from both sides and when the boss comes out of the ground it slows down a lot when you've got 2 "shadow ninjas" with you and upgraded sword.

For Sprite limit I've just tried with Darius Alpha and I can see the 1st boss stops flickering after a reboot.
So it's working fine.

For the overscan range we changed some stuff in pce_fast to display the full range and have PAR by default, centred picture and width settings for games in 341 mode (ninja spirit, aoi blink, r-type (japan only)...). But those changes can break some things (like positioning of small pics on screen in Final Blaster intro, that's why we added a hack for that).

**Comment by trinemark** [comment]
Thanks for explaining. H-Overscan is now hooked up.

Although now I understand. 341 is the supposed traditional / nominal width (per Mednafen docs). But you can adjust up (352) and down (300) the overscan clipping range. I might revisit this again later for more alterations. I can imagine some people wanting 1:1 PAR option, whereas core currently stretches to locked 341 width.

**Comment by retro-wertz** [comment]
nice work. hope core wont get too hacked like the pce_fast has been...

**Comment by Tatsuya79** [comment]
H-overscan is just cutting in the right side, left is always the same.

**Comment by retro-wertz** [comment]
think you need to directly modify mode 1 in add_dot_scanline to be variable one...

**Comment by hizzlekizzle** [comment]
Re: bounty, I believe we can transfer it over to another existing bounty without too much trouble.

**Comment by trinemark** [comment]
@Tatsuya79 
I think overclocking (cpu, cd) are now fixed. Sprite limit can be done in real-time. 5-player Bomberman works. Tested CD PSG slider and volume goes up / down.

Ninja Spirit sound clicks. Can you make a Retroarch audio recording? I can't hear this. Sounds same to me with Beetle PCE Fast so I'm missing something.


https://pineight.com/mw/index.php?title=Dot_clock_rates
8:7 (256), 6:7 (352), 4:7 (512).

So this says 8/6 = 4/3 pixel stretch. Which is where 341 - 341.3333333 - 342 cropping comes from. But it can overscan to 352 but keeps same par. And our dar would get thrown off. Plus TVs who can show / hide the extra overscan pixels so left - right crop needed. Needs more though; cpu overclocking required fractional cycle counting for pce accurate to avoid event de-syncing.

Haven't checked 240+ overscan area yet.

**Comment by Tatsuya79** [comment]
Overclocking is working now nice!.

Order of the Griffon is still wrong. 
What happens is the top of the picture showing the main game in pseudo 3D is 256px width while the bottom with the characters portraits and stats is using the 341 pixels mode.
It's changing the resolution middle frame and I think the way mednafen does it is by rendering at a higher horizontal res? ([PR adding a hack in pce_fast with a link to another method which I'm really not sure can work here?](https://github.com/libretro/beetle-pce-fast-libretro/pull/74))

About the sound clicks, it's in every game more or less, but I find a good example using [Cyber Core sound test](https://tcrf.net/Cyber_Core_(TurboGrafx-16)) with SE 09.


[cyber core samples.zip](https://github.com/libretro/beetle-pce-fast-libretro/files/3089166/cyber.core.samples.zip)

**Comment by trinemark** [comment]
Mednafen 1.22.1. Order of Griffin looks roughly the same as Beetle PCE atm. 256 view stretching. Or is there a hidden option? Using vanilla defaults.

I do see what Beetle PCE Fast does with the pillarbox. It probably can be done since it should tie into 352 cropping.

But does anyone have a screenshot of real hardware + CRT TV?

**Comment by Tatsuya79** [comment]
You can see some capture videos on youtube [here](https://www.youtube.com/watch?v=K7mjDp6zbCA) or [here](https://www.youtube.com/watch?v=BJPMh-ZJytY).
It's like mednafen stand-alone for the aspect ratio of each part of the screen, the difference is that if you render it in 342 pixels width the 256 width part on top will have noticeable uneven pixels.
A crt doesn't work the same and won't do that.

But here with RA we have to decide of a way to handle that and specify a width. 
If it's 2048 or something it will be close to an integer value for both parts so that it's not too visible.
Then it's about what's acceptable or not, I'm not sure what mednafen chooses, 1365 pixels I saw somewhere?

**Comment by trinemark** [comment]
Uneven hard pixels. Large width for nice integer scaling. Okay, I'm with you now.

Mednafen has a 1365 width buffer. There's PCE TA_AwesomeMode which expands everything to 1024 using real-time dot clock drawing, but it creates glitchy scanlines towards the bottom.

I will create a fork for this and give it some more thought.

**Comment by trinemark** [comment]
1365 dot clocks per scanline. But that's a messy number to work with.

Mednafen (internally) draws a nominal 1024 due to scaling math:
```
256 512 768 1024 1280 1536 1792
341   682   1023   1364  1705
342   684   1026   1368  1710
```

I'd agree that 342 is the nominal width. Games seem to draw 342 pixels over 341. Although this may matter less once adjustable cropping kicks in.

Might also try to include a core option to render like PCE Fast with pillarbox.

I'll work on this first and post a test branch.

**Comment by Tatsuya79** [comment]
I found a good example of the bad refresh in the vertical overscan, it's easy to see with PC Genjin if you display 242 lines on the bottom of the screen.
I don't think mednafen goes as far upstream and we changed that to get the full signal (as it was displayed on Turbo GT and because many games have valid signal there so why not).

Some games had their picture not centred and cut too before we changed it like Super Darius (CD game).
![Super Darius (J)-190417-174649](https://user-images.githubusercontent.com/6266038/56301978-2b5c2500-6139-11e9-9349-51660f6a114b.png)

**Comment by Tatsuya79** [comment]
Ah I found what's causing the audio clicks.
There's a setting called pce.psgrevision that is probably forcing the SGX audio chip and causing clicking [as explained in this page.](https://mednafen.github.io/documentation/pce.html)

[I tried to force "return 1" on this line](https://github.com/trinemark/beetle-pce-fast-libretro/blob/pce/mednafen/settings.cpp#L68) and the clicking is gone.

That's a setting that wasn't in pce_fast. There's pce.resamp_quality too and perhaps some more.

**Comment by trinemark** [comment]
Thanks for finding that. Although now I'm wondering a bit before I get a chance to test.
```
	enum
	{
		REVISION_HUC6280 = 0,
		REVISION_HUC6280A,
		_REVISION_COUNT
	};
```

By default, it's _REVISION_COUNT which auto-selects.
```
psgrevision = IsSGX ? PCE_PSG::REVISION_HUC6280A : PCE_PSG::REVISION_HUC6280;
```

A value of 1 would always force 6280A (or at least it's supposed to do that). I'll debug check this to be sure.

Reminds me of the two MT-32 revisions; some old Sierra games relied on REV0 for its sfx.

**Comment by Tatsuya79** [comment]
Well, something particular vs pce_fast once again is the pce.h_overscan setting that will enlarge the width [following those values](https://github.com/trinemark/beetle-pce-fast-libretro/blob/pce/mednafen/pce/vce.cpp#L577) I assume.
When enabled I can finally see the Ninja spirit logo completely (352 width) and Super Darius won't cut the right of the picture anymore (but the image isn't centred).
(while you can show the full range on original machines, I checked that again for Super Darius:
https://www.youtube.com/watch?v=0CzO062iIt4
https://www.youtube.com/watch?v=wrEk3SybZGw
and for Ninja Spirit:
https://youtu.be/hl0IG8QAnrc?t=261
https://www.youtube.com/watch?v=hNWyydIglHA )

It messes up the image ratio though and the picture can be off-centred for the 256 width mode too (as in super darius).
So I'm not sure we want to break mednafen rendering too much (as in changing what is defined for different width modes in vce.cpp, that's the "accuracy" version of the core here) or add many "crop left, crop right" options for each resolution...

So I wonder, the easiest solution could be:
-exposing pce.h_overscan as an option and try to adapt the screen ratio when enabled
-have another option called "Auto centre the picture (hack)" that would do something similar to pce_fast and force 256/352/512 with centred pic
-have the same horizontal cropping option as pce_fast that cut both sides then

mmm writing that down I'm not even sure that's the best way and can be easily done lol. But I post it anyway for discussion.

**Comment by Tatsuya79** [comment]
About the bottom lines refresh problem when showing 242, it can be fixed by changing every 240 mention by 243 in vce.cpp (there's 3 spots).
Yeah I know, after advocating for not changing values too much I suggest that. :sweat_smile: 
But I don't know why mednafen is limiting to 239 while 242 are valid in most games and displayed on Pc Engine GT.

[Not sure about that comment here](https://github.com/trinemark/beetle-pce-fast-libretro/blob/pce/mednafen/pce/vce.cpp#L305) 263-14=249. (I blindly tried that but that crashed)

**Comment by trinemark** [comment]
I'll just make a "Vertical overscan scanlines" = 240, 243 option. I'm also going to eventually put back the 341 numbers and work with expanded overscan math, which is going to be messy math for me.

Thanks for all the help btw. Making this unfamiliar stuff easier to handle.

**Comment by trinemark** [comment]
https://forum.fobby.net/index.php?t=msg&goto=675
>Once the screen width has been set, then the VDC's registers like HDR, HSR, etc. are set up to center the display. For example some games use the 352-pixel mode and center a 320-pixel screen in the middle.

So by default we're supposed to auto-center the picture somehow, and take into account any h-overscan. That could be brutal.

I'd vote for an "auto" type of horizontal overscan detection. Although this is getting stickier than I wanted.

>edit: perhaps just pce.h_overscan and independent crop left and right that would work for every mode.

This'd be good too as a fallback, if the math magic starts to fail us. But this is all cloud thinking until someone pushes something through.

I think Asuka 120% uses 256 - 512 (no 341) multires, so I'll account for this also.

**Comment by Tatsuya79** [comment]
I already brought the overscan shortcomings to mednafen author some years ago but it's probably not a priority for her. I can't blame her as she made a great Saturn emulator meanwhile, these kind of things happen.

Everything is rendered at a really large width right now, it's just temporary right?

**Comment by trinemark** [comment]
The full accurate mode (hires dot clock renderer) has to be 1024 + 96 overscan. It has some nice simplicity to it since it can handle the extra crazy pixels: tomaitheous says lores = 274, midres = 368 (Tenchi o Kurau), hires = 548. Even 256px in midres mode for vertical shmups. And cleans up any multires overscan scaling problems.

The overscan stuff needs a working framework. I am writing an idea that might work much of the time for horizontal auto-cropping and centering mode. Then if we can get away with it, I'd like to reduce the buffer again. Even if it means de-scaling the data back down when we're not in midres multi-res mode (maybe just 1 game).

But well. I'd never expect the PC Engine to be so flexible for a 6502-era system. Beats the Atari 2600 multi-fps switching modes. If I worked even half a decade on this system, I'd get tired and drift elsewhere.

**Comment by trinemark** [comment]
Mednafen uses some slightly non-standard overscan and resolution widths. Working out the math slowly. Super Darius is 256 cropped and centered. Final Blaster looks almost okay - need an adjustment somewhere. 352 mode is not so nice yet.

Also fixed par math. (float) width / (float) height. Else compiler goes strict with (int) width / (int) height * (float) par = off by enough pixels.

**Comment by trinemark** [comment]
Auto-crop horizontal overscan is now in. This will need lots of testing. Note that some games seem to enable overdraw with either blank dummy or garbage tiles.

I can't blindly clip this out and I suppose we'll need another h-crop flag: 8px left, 8px right, 16px both. But you're the game experts and know what extra clipping we need, whether per line or such.

For Order of the Griffin, I'm unsure whether players want the current 320 auto-crop look or the standard  341 view. Or toggle between them somehow.

Since it works well enough so far and passes 240p test suite, I'll look into providing lower res scaling options.

**Comment by Tatsuya79** [comment]
There is this issue on compilation:
```cpp
libretro.cpp: In function 'void update_input()':
libretro.cpp:877:27: error: 'roundf' was not declared in this scope
    mousedata[j][0] = (int)roundf(_x * mouse_sensitivity);
                           ^~~~~~
libretro.cpp:877:27: note: suggested alternative: 'rand'
    mousedata[j][0] = (int)roundf(_x * mouse_sensitivity);
                           ^~~~~~
                           rand
```
Also it's missing the crop overscan core option.

**Comment by trinemark** [comment]
```#include <math.h>```

Also realized that Addams Family and Asuka 120% might be rendering past the active draw area. If so, I can auto-crop that 8px garbage out.

**Comment by Tatsuya79** [comment]
352 wide games have a slight rounding problem that removes 1 pixel on the left side, 1 black on the right side.
![Saigo no Nindou - Ninja Spirit (Japan)-190421-113820](https://user-images.githubusercontent.com/6266038/56472973-6de96e80-6465-11e9-9568-c52e9bdedc85.png)
![R-Type Part-2 (Japan)-190421-181043](https://user-images.githubusercontent.com/6266038/56472979-7b9ef400-6465-11e9-90c6-3556257d90ba.png)

Addams family too is cut slightly on the left and shows a bit of garbage on the right:
![The Addams Family (U)-190421-184008](https://user-images.githubusercontent.com/6266038/56472985-9ec9a380-6465-11e9-9159-cfc27087d11e.png)

Asuka 120 looks fine except on this screen when starting the story mode (this problem also happens in pce fast, we didn't bother with it):
![Asuka 120% Maxima Burning Fest (J)-190421-181513](https://user-images.githubusercontent.com/6266038/56473033-28797100-6466-11e9-94f2-4b97726f809a.png)
![Asuka 120% Maxima Burning Fest (J)-190421-181512](https://user-images.githubusercontent.com/6266038/56473037-2ca58e80-6466-11e9-8736-11ca43dd5c5a.png)

Tv Sport Basketball 512 wide picture is cropped too much:
![TV Sports Basketball (Japan)-190421-183456](https://user-images.githubusercontent.com/6266038/56473053-45ae3f80-6466-11e9-8a54-0f3a7e1e27c3.png)
![TV Sports Basketball (Japan)-190421-183510](https://user-images.githubusercontent.com/6266038/56473054-4646d600-6466-11e9-914c-6a0773ce9ee7.png)

Same for [Flappy Bird](http://buildbot.libretro.com/assets/cores/NEC%20-%20PC%20Engine%20SuperGrafx/):
![flappy_bird_SGX-190421-183602](https://user-images.githubusercontent.com/6266038/56473060-578fe280-6466-11e9-986e-93b348b76e18.png)
![flappy_bird_SGX-190421-183614](https://user-images.githubusercontent.com/6266038/56473061-58287900-6466-11e9-9c9d-7f5702bd1173.png)

Super Darius is fine.
Order of the Griffon too, apart for that slight rounding issue again in that menu:
![Order of the Griffon (USA)-190421-185306](https://user-images.githubusercontent.com/6266038/56473122-ea308180-6466-11e9-8cd6-caae85fe38d5.png)

I've compared 1056 vs 352 width mode on an older core, 352 is 20% faster.

**Comment by trinemark** [comment]
512 off-centered was due to overdraw crop detection. That should be fixed. Auto-res scaler is now in, although Asuka dialog is still (256, 512) hires atm.

Dot scaler must be doing that rounding. I'll +1 it somewhere.

Thanks. Please check git again.

**Comment by Tatsuya79** [comment]
Tv Sport and Flappy bird are fine now. :+1: 

I tried low res mode but that's what I feared, 400fps vs 500fps before when we didn't have the big framebuffer + downscaling operations. :confused:

**Comment by trinemark** [comment]
Asuka 120% dialogue box looks okay on my end now.

Mednafen core wants us to pre-select renderer at compile time. I'll try adding a switch and doing the multi-res myself.

**Comment by trinemark** [comment]
Lores scaler is now in. Multi-res (auto, lores) is broken.

**Comment by Tatsuya79** [comment]
Sorry to tell you, but it's slower now, around 350fps on my same test on Ninja Spirit (auto/auto and lores/h overscan off giving the same speed). :confused: 
Too much overhead with conditions in intensive spots?

For lores 256+352 it's mainly order of the griffon where some characters stats will be cut on each sides if you crop to 256. Better use 352.

**Comment by icetoffee** [comment]
For D&D lores only, I was thinking of making dungeon view a centered 256. The status bar would still be 320, since game tells vdp to draw that many pixels for those scanlines. Or do you think it'd be better to just scale the 256 up to 320 and deal with any janky cuts?

I guess slower speed explains why Mednafen chose to template inline it. I'll switch to that.

**Comment by trinemark** [comment]
It should be better now but maybe some bit slower still. Might look for some tuneups.

For Order of Griffin (lores mode), would everyone prefer 256 -> 320 dungeon view or centered 256 view? Game only draws 320 pixels for status bar, which is what we auto-crop to.

**Comment by Tatsuya79** [comment]
Centred 256 I'd say. Uneven pixels are too noticeable if stretched to such a low resolution.

**Comment by Tatsuya79** [comment]
I went back to make sure at which point we lost 20% perf and [it's in that commit](https://github.com/trinemark/beetle-pce-fast-libretro/commit/75f28514b99b2ae25b4bbaa7ff75093423fb1868). [(with that fix too)](https://github.com/trinemark/beetle-pce-fast-libretro/commit/cc81597f5eb22c862cf631c417873079b71a78d4)

**Comment by trinemark** [comment]
Test1 is:
https://github.com/trinemark/beetle-pce-fast-libretro/blob/pce/mednafen/pce/vce.cpp#L608
https://github.com/trinemark/beetle-pce-fast-libretro/blob/pce/mednafen/pce/vce.cpp#L610
```
SyncSub<true, false>(clocks)
SyncSub<false, false>(clocks)
```

Test 2 is:
https://github.com/trinemark/beetle-pce-fast-libretro/blob/pce/libretro.cpp#L35
https://github.com/trinemark/beetle-pce-fast-libretro/blob/pce/libretro.cpp#L36
```
#define MEDNAFEN_CORE_GEOMETRY_MAX_W 1024 + 96
#define MEDNAFEN_CORE_GEOMETRY_MAX_H 243
```

I don't see any changes with either. You might want to turn on the debug logger and see how the resolution changes are being reported. They should be nice and small at non-hires.

**Comment by Tatsuya79** [comment]
Still around 350 fps for all 3 tests.

I tried removing, replacing some parts but I can't go back to 500fps like it was prior to https://github.com/trinemark/beetle-pce-fast-libretro/commit/75f28514b99b2ae25b4bbaa7ff75093423fb1868 .

**Comment by trinemark** [comment]
Got a brief break. Created appveyor account. Check here for some sample builds.
https://ci.appveyor.com/project/trinemark/beetle-pce-fast-libretro/history

**Comment by Tatsuya79** [comment]
Thanks, it's quite the same as gcc.
Msvc being just a tad slower on the previous "render 241+ scanlines correctly" commit vs GCC, but still losing a good 100fps on the "use dot clock renderer" changes.

Similar speed on initial commit.

I don't fully understand mednafen code but I wonder if removing the part that was doing the counting (dot_scanline_count) and [signalling the end of the frame](https://github.com/trinemark/beetle-pce-fast-libretro/commit/cc81597f5eb22c862cf631c417873079b71a78d4) isn't wasting some cycles or something.

**Comment by trinemark** [comment]
I added ```add_dot_scanline``` to figure out when scanlines start changing resolution widths. Removed it when we switched to hires renderer.

Try this test1 build. It reorders the branches and I get a small boost but nowhere near 100 fps.
https://ci.appveyor.com/project/trinemark/beetle-pce-fast-libretro/builds/24017922

**Comment by Tatsuya79** [comment]
They both give the same speed, around 370fps with msvc, 350fps if I compile myself with GCC just like you said (I didn't mention it before but it was happening near current commits).

**Comment by trinemark** [comment]
Guess I'll start working backwards.
https://ci.appveyor.com/project/trinemark/beetle-pce-fast-libretro/builds/24020574

**Comment by Tatsuya79** [comment]
Yeah I verified my checking many times, even tried without g-sync just in case but it's always the same...
And I always get around 500fps again with older cores.

Try it for yourself with the initial commit core and the one before the big slow down, so we'll be sure it's not my computer.

**Comment by trinemark** [comment]
I'm on an older work machine atm.
initial ~ 164
pre-dot ~ 156
test1 (latest) ~ 152

**Comment by Tatsuya79** [comment]
Ok so you're losing a good 20% on that commit, same as me.
Just that I regain nothing from the test1 branch here. :confused:

**Comment by Tatsuya79** [comment]
Testing the commit prior to the slow down and just changing these 2 lines as:
```cpp
SyncSub<true, true>(clocks)
SyncSub<false, true>(clocks)
```
is enough to lose 20% perf.

Earlier I was starting from the slower commit and trying to do the opposite, which wasn't recovering the speed loss.

**Comment by trinemark** [comment]
> Earlier I was starting from the slower commit and trying to do the opposite, which wasn't recovering the speed loss.

If you start at the dot clock commit and continue onward, changing all lines back to
```
SyncSub<true, false>(clocks)
SyncSub<false, false>(clocks)
```
which is 1st commit speed recovers nothing?

**Comment by Tatsuya79** [comment]
Not sure I got what you're asking, but I tried again from https://github.com/trinemark/beetle-pce-fast-libretro/commit/cc81597f5eb22c862cf631c417873079b71a78d4
just putting back
```cpp
SyncSub<true, false>(clocks)
SyncSub<false, false>(clocks)
```
makes it go back to around 500fps again. 

Not sure what I did before, I thought it didn't work. :sweat: 
(It looks wrong though with a bad aspect.)

**Comment by trinemark** [comment]
Thanks a lot for figuring this out! MDFN_GetSettingUI is a very large if-else block. SyncSub is called often enough that it wastes lots of time checking something that is already known.

By moving it into StartFrame, it won't change again anyway. Smart discovery and fix!

**Comment by Tatsuya79** [comment]
Thanks! but thanks for your work here too! :smiley: 

On a different clicking note, I've just tested audio on mednafen stand-alone (now that I found that gsync was the culprit for causing a driver recovery with it...) and it's just like in libretro.
It's fine with huc6280a while default "match" or huc6280 are causing clicks.

**Comment by trinemark** [comment]
Multi-res renderer is in. Other than replacing with NTSC clock math and maybe optional arcade card emulation, that's about it for me. Going to skip C++11 removal, given how long all this took.

Although I do see maybe a couple things to try for small speedup.

**Comment by Tatsuya79** [comment]
I tried various games at low/high res, everything seems fine.
Good work, that's pretty cool now. :smiley: 
[
Mednafen has just been updated.](https://forum.fobby.net/index.php?t=rview&goto=5834&th=1788#msg_5834)

She also responded to [my message about the sound here.](https://forum.fobby.net/index.php?t=msg&th=1358&start=0&)
I'm still a bit mixed about that, every game I can test even old ones always have clicks with the default setting. Perhaps the original sound chip was like that? or is there really an issue?
I would put the default in the core to huc6280a really; this is inferior to what we have in the other cores on the current default. 
When set on huc6280a it's also better than the fast cores I'd say; a bit clearer with higher notes more defined (overall less muddy).

Perhaps we can remove the crop left/right settings as they're not used now?

Only thing I can think of that could be added is horizontal pixel blending in hires to make the transition between high/low res modes less evident (like in order of the griffon between the action and the menu/inventory).
[There's that code in snes9x.](https://github.com/libretro/snes9x/blob/master/libretro/libretro.cpp#L1776)

**Comment by trinemark** [comment]
Since it is a libretro core and not involved with upstream, sure we can default to huc6280a.

Didn't see any good updates since we don't support hes files. Left / Right crop I haven't found a use yet either - auto-crop seems to handle pretty well.

Hmm. Pixel blending for hires mode. It's a thought to look into.

**Comment by Awakened0** [comment]
@trinemark and @Tatsuya79 , great work! I've compiled a build of this from @trinemark 's fork and everything works great from testing a few games. I mainly just use the initial/last scanline and audio volume options to tweak cropping and balance the audio for certain games. Those options look to be working just as well as they do in Fast. It's nice to have these new audio options exposed too.

One thing I wanted to request as I messing around with Bonk, is an option to make Retropad Y and X into dedicated turbo I and II buttons. Kind of like the Alternate Toggle option makes them into toggles.

**Comment by trinemark** [comment]
Tatsuya79 did an amazing job pointing out every small issue, trying to maintain parity with Fast and Super Grafx cores. Also contributed a new blur method.

Kinda forgot already what I added recently but I'm nearly done now. Just some tune-up ideas to try out. Although I curiously wonder if it's possible to auto-control the vertical scanlines based on vdp drawing registers.

I like the idea of (Y,X = dedicated turbo I,II).

**Comment by Tatsuya79** [comment]
The blending option I modified is bad, I was about to kill it! :sweat_smile: 
It acts strangely on the left side, try it at max "8" on a standard 256 wide game in hires mode, you'll see.

I can't see how to fix that... perhaps it's not needed as we can always force 1024 width and use a shader with a parametric horizontal blur anyway.

**Comment by Tatsuya79** [comment]
Ok I got it somewhat acceptable now I guess.

**Comment by trinemark** [comment]
New blur merged. And turbo hotkeys can now be switched to dedicated I,II turbo buttons.

Although now I notice we're missing 6-button joypads. Skipping speedups as I didn't get anything worth committing.

**Comment by Tatsuya79** [comment]
Nice work, pretty complete now. :+1: 

It should be time to bring it on the buildbot as an official core.
Push it as a branch to libretro pce_fast I guess?

**Comment by trinemark** [comment]
Not going to put in auto-vertical scanline for now. There's some strange cases that don't fit the math nicely. But generally many games do like to display 240 scanlines total, so that's where 3-242 comes in.

Got my last commit in and I'm done with Phase 1. Others can take over once it's on the libretro line.

**Comment by Tatsuya79** [comment]
It's added here as a branch.
I added the core info and the buildbot recipes should be merged soon.

You can claim the bounty or choose to put it on something else if you don't want it.

**Comment by trinemark** [comment]
Great. Thanks!

Bounty owners can transfer to wherever they please; I'll skip on it since Mednafen author is the one who did the real bulky hulky work.

**Comment by Tatsuya79** [comment]
It's not building for [osx ](http://p.0bl.net/116209)and [linux](http://p.0bl.net/116262).

**Comment by trinemark** [comment]
https://github.com/fortpar/beetle-pce-fast-libretro/blob/work/Makefile#L74
```
CXXFLAGS += -fpermissive -std=c++11
```

You'll have to add
```
CXXFLAGS += -std=c++11
```
for all other failing builds.

**Comment by Tatsuya79** [comment]
OSX64 succeeded now but other ones failed:

mednafen_pce: [status: fail] [recipes/apple/cores-ios-generic] LOG: http://p.0bl.net/116462
mednafen_pce: [status: fail] [recipes/apple/cores-ios9-generic] LOG: http://p.0bl.net/116463
mednafen_pce: [status: fail] [recipes/linux/cores-linux-x64-generic] LOG: http://p.0bl.net/116518
mednafen_pce: [status: fail] [recipes/linux/cores-linux-armhf-generic] LOG: http://p.0bl.net/116520
mednafen_pce: [status: fail] [recipes/linux/cores-linux-arm7neonhf] LOG: http://p.0bl.net/116523
mednafen_pce: [status: fail] [recipes/windows/cores-windows-msvc2010-x64_seh-generic] LOG: http://p.0bl.net/116560
mednafen_pce: [status: fail] [recipes/windows/cores-windows-msvc2010-x86_dw2-generic] LOG: http://p.0bl.net/116565

**Comment by trinemark** [comment]
For (2) ios, try this:
https://github.com/libretro/beetle-pce-fast-libretro/blob/master/mednafen/mednafen-types.h#L34
```
  #define MDFN_ALIGN(n)	__attribute__ ((aligned (n)))
  #define MDFN_FORMATSTR(a,b,c) __attribute__ ((format (a, b, c)));
  #define MDFN_WARN_UNUSED_RESULT __attribute__ ((warn_unused_result))
  #define MDFN_NOWARN_UNUSED __attribute__((unused))
  #define MDFN_ASSUME_ALIGNED(p, align) (p)```
```

For (3) linux, retry:
```
ifneq (,$(findstring unix,$(platform)))
   TARGET := $(TARGET_NAME)_libretro.so
   fpic := -fPIC
   SHARED := -shared -Wl,--no-undefined -Wl,--version-script=link.T
   CXXFLAGS += -fpermissive -std=c++11
   ifneq (,$(findstring Haiku,$(shell uname -s)))
   LDFLAGS += -lroot
   else
   LDFLAGS += -lrt
endif
```

For (2) msvc2010, I don't think it supports c++11 (alignas). Likely have to wait for someone to rip it all out.

**Comment by Tatsuya79** [comment]
Thanks, I'll just try Linux as I'm not sure if it's a typo for ios (``` at the end) and I can't test it. :sweat_smile:

**Comment by trinemark** [comment]
Oops. It's gone now. I can't compile ios either but linux I didn't have any problems before the c++11 switch. Hopefully it all works on the buildbot.

**Comment by trinemark** [comment]
Most of the c++11 must've been removed earlier. Mopped up the rest and that should solve everyone's ports.

**Comment by Tatsuya79** [comment]
I saw that Linux and iOS built fine now. :+1:

**Comment by trinemark** [comment]
Something that puzzled me about 2010 is that it works with PCE Fast. So it must be some new files that broke it.

I saw 2 files that use snprintf and patched those up. If it still fails, please upload a buildbot log since it should be close to working.

**Comment by Tatsuya79** [comment]
mednafen_pce: [status: done] [recipes/windows/cores-windows-msvc2010-x86_dw2-generic]
mednafen_pce: [status: done] [recipes/windows/cores-windows-msvc2010-x64_seh-generic]

Not sure what it is for but it's working now! :ok_hand:

**Comment by richterdeveloper** [comment]
Excelent work!!! By the way, the Game Express games don't work. I don't know if this is a v0.9.48 bug or not. In the PCE-Fast core and the lastest Mednafen standalone works without problem.

Thanks!!!

**Comment by funbars** [comment]
non-cd games work
https://necretro.org/Games_Express

is problem with cd games?

**Comment by Tatsuya79** [comment]
Indeed Games Express CD games are crashing with that message in the logging window:

```
unhandled setting S: pce.gecdbios
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
```

**Comment by Tatsuya79** [comment]
It works [if I force pce.cdbios on this line.](https://github.com/libretro/beetle-pce-fast-libretro/blob/pce/mednafen/pce/pce.cpp#L500)
Or we could use the auto-detect method?

**Comment by funbars** [comment]
Alternate.
https://github.com/funbars/beetle-pce-fast-libretro/commit/7640f38b5fca469589fb130376966a3a69173618

**Comment by Tatsuya79** [comment]
Yes that works.
So it will auto-detect games express games but we can still override it the core options if the game isn't recognized (hacks/translations).

We don't even need the change in settings.h.

**Comment by Tatsuya79** [comment]
And the run ahead fix is working fine, I wasn't sure if that was right to do it like this.
Thanks for that!

**Comment by funbars** [comment]
> We don't even need the change in settings.h.

Oh. Remove during next clean up or sometime. :)

> And the run ahead fix is working fine, I wasn't sure if that was right to do it like this.

Could work for other cores with runahead problem. Put aside large memory buffer.

**Comment by SedrynTyros** [comment]
Hey guys, where's the repository for this new mednafen accurate pce core you're working on?  A lot of the links in this thread go nowhere.

**Comment by Awakened0** [comment]
It's in this repo, in the pce branch: https://github.com/libretro/beetle-pce-fast-libretro/tree/pce

**Comment by SedrynTyros** [comment]
> It's in this repo, in the pce branch: https://github.com/libretro/beetle-pce-fast-libretro/tree/pce

Thanks!  A bit confusing that the repo is labelled "beetle-pce-fast ..." but whatever.  As long as I know where to find it.

**Comment by twinaphex** [comment]
OK, the bounty has finished and we should move to close this.

Question to the bounty backers - the bounty hunter is gone and this were his last thoughts on the matter - 

'@hizzlekizzle
If the bounty owners wish to donate directly to libretro or any emu author, that'd be preferred. I myself won't be collecting on it.'

Are you guys OK with the money going to us in this case?

**Comment by mrjschulte** [comment]
Fine by me :)

**Comment by mrjschulte** [comment]
Btw, for everyone on this thread still keeping score: 
The pce branch has been promoted to being its own core in RA called mednafen_pce

**Comment by negativeExponent** [comment]
done! and pce core already has its own repo.

**Comment by Eggo-dotcom** [comment]
will this core ever be updated? lots of fixes to pce accurate since 9.48
